export type { Position, Point } from "./position";
export { createPoint, createPosition } from "./position";

// Version type
export type Version = "wikidot";

// Element types (output AST)
export type {
  Element,
  ElementName,
  ElementData,
  ElementOf,
  ElementDataMap,
  SyntaxTree,
  ContainerType,
  StringContainerType,
  ContainerData,
  AttributeMap,
  VariableMap,
  Alignment,
  LinkType,
  LinkLocation,
  LinkLabel,
  PageRef,
  ImageSource,
  FloatAlignment,
  ListType,
  ListItem,
  ListData,
  CodeBlockData,
  TabData,
  TableCell,
  TableRow,
  TableData,
  DefinitionListItem,
  Module,
  CollapsibleData,
  ClearFloat,
  AnchorTarget,
  HeaderType,
  AlignType,
  HeadingLevel,
  Heading,
  DateItem,
  Embed,
  TocEntry,
  AnchorData,
  LinkData,
  ImageData,
  TableOfContentsData,
  FootnoteBlockData,
  BibliographyCiteData,
  BibliographyBlockData,
  UserData,
  DateData,
  ColorData,
  MathData,
  MathInlineData,
  HtmlData,
  IframeData,
  IncludeData,
  IfTagsData,
  ExprData,
  IfCondData,
  IfExprData,
} from "./element";
export {
  text,
  container,
  paragraph,
  bold,
  italics,
  heading,
  lineBreak,
  horizontalRule,
  link,
  list,
  listItemElements,
  listItemSubList,
  isStringContainerType,
  isHeaderType,
  isAlignType,
  isContainerTypeParagraphSafe,
  isParagraphSafe,
} from "./element";
