import { describe, expect, it } from "bun:test";
import {
  processWikitext,
  type PageData,
  type ProcessWikitextDataProvider,
  type SiteContext,
} from "@wdprlib/parser";
import { DEFAULT_SETTINGS, type Element, type WikitextPageContext } from "@wdprlib/ast";

const pageContext: WikitextPageContext = {
  fullName: "docs:pipeline",
  unixName: "pipeline",
  tags: ["component"],
  urlPath: "/docs:pipeline/offset/0",
};

function pageData(title = "Generated"): PageData {
  return {
    name: "generated",
    category: "_default",
    fullname: "generated",
    title,
    createdAt: new Date("2026-07-23T00:00:00Z"),
    updatedAt: new Date("2026-07-23T00:00:00Z"),
    tags: [],
    hiddenTags: [],
    children: 0,
    comments: 0,
    size: 0,
    rating: 0,
    ratingVotes: 0,
    revisions: 1,
  };
}

function siteContext(): SiteContext {
  return { name: "test", title: "Test", domain: "test.example" };
}

function listPagesProvider(
  overrides: Partial<ProcessWikitextDataProvider<WikitextPageContext>> = {},
): ProcessWikitextDataProvider<WikitextPageContext> {
  return {
    fetchListPages: async () => ({
      pages: [pageData()],
      totalCount: 1,
      site: siteContext(),
    }),
    ...overrides,
  };
}

describe("processWikitext", () => {
  it("propagates one page and settings context to include and module callbacks", async () => {
    const contexts: unknown[] = [];
    const settings = {
      ...DEFAULT_SETTINGS,
      useTrueIds: false,
    };

    const document = await processWikitext(
      ["[[include shared]]", '[[module ListPages range="." limit="1"]]x[[/module]]'].join("\n"),
      {
        page: pageContext,
        settings,
        dataProvider: {
          fetchInclude: async (_pageRef, context) => {
            contexts.push(context);
            return "included";
          },
          fetchListPages: async (_query, _requirement, context) => {
            contexts.push(context);
            return {
              pages: [pageData()],
              totalCount: 1,
              site: siteContext(),
            };
          },
        },
      },
    );

    expect(contexts).toHaveLength(2);
    expect(contexts[0]).toBe(contexts[1]);
    expect(contexts[0]).toEqual({ page: pageContext, settings });
    expect(document.page).toBe(pageContext);
    expect(document.settings).toBe(settings);
  });

  it("merges ListPages HTML, footnotes, CSS, code and TOC side channels", async () => {
    const source = [
      '[[module ListPages range="." limit="1"]]',
      "+ %%title%%",
      "[[html]]<p>list-pages</p>[[/html]]",
      "[[footnote]]ListPages note[[/footnote]]",
      "[[code]]list-pages-code[[/code]]",
      "[[module CSS]]",
      ".list-pages { color: red; }",
      "[[/module]]",
      "[[/module]]",
    ].join("\n");

    const document = await processWikitext(source, {
      page: pageContext,
      dataProvider: listPagesProvider(),
    });

    expect(document.ast["html-blocks"]).toEqual(["<p>list-pages</p>"]);
    expect(document.ast.footnotes).toHaveLength(1);
    expect(document.ast.styles).toEqual([".list-pages { color: red; }"]);
    expect(document.ast["code-blocks"]?.[0]?.contents).toBe("list-pages-code");
    expect(document.ast["table-of-contents"]).toHaveLength(1);
  });

  it("merges every ListUsers side channel", async () => {
    const source = [
      '[[module ListUsers users="."]]',
      "+ %%title%%",
      "[[html]]<p>list-users</p>[[/html]]",
      "[[footnote]]ListUsers note[[/footnote]]",
      "[[code]]list-users-code[[/code]]",
      "[[module CSS]]",
      ".list-users { color: blue; }",
      "[[/module]]",
      "[[/module]]",
    ].join("\n");

    const document = await processWikitext(source, {
      page: pageContext,
      dataProvider: {
        fetchListUsers: async () => ({
          user: { number: 1, title: "Alice", name: "alice" },
        }),
      },
    });

    expect(document.ast["html-blocks"]).toEqual(["<p>list-users</p>"]);
    expect(document.ast.footnotes).toHaveLength(1);
    expect(document.ast.styles).toEqual([".list-users { color: blue; }"]);
    expect(document.ast["code-blocks"]?.[0]?.contents).toBe("list-users-code");
    expect(document.ast["table-of-contents"]).toHaveLength(1);
  });

  it("expands includes generated by modules and combines dependency order", async () => {
    const sources: Record<string, string> = {
      top: "top\n[[include nested]]",
      nested: "nested",
      generated: "generated\n[[include generated-child]]",
      "generated-child": "child",
    };
    const fetchCount = new Map<string, number>();
    const source = [
      "[[include top]]",
      '[[module ListPages range="." limit="1"]]',
      "%%title%%",
      "[[/module]]",
    ].join("\n");

    const document = await processWikitext(source, {
      page: pageContext,
      dataProvider: listPagesProvider({
        fetchListPages: async () => ({
          pages: [pageData("[[include generated]]\n[[include nested]]")],
          totalCount: 1,
          site: siteContext(),
        }),
        fetchInclude: async ({ page }) => {
          fetchCount.set(page, (fetchCount.get(page) ?? 0) + 1);
          return sources[page] ?? null;
        },
      }),
    });

    expect(document.dependencies.map((item) => item.location.page)).toEqual([
      "top",
      "nested",
      "generated",
      "nested",
      "generated-child",
    ]);
    expect(fetchCount.get("nested")).toBe(1);
  });

  it("keeps HTML and footnote order across top-level and multiple modules", async () => {
    const source = [
      "[[html]]top[[/html]]",
      "[[footnote]]top note[[/footnote]]",
      '[[module ListPages range="." limit="1"]]',
      "[[html]]pages[[/html]]",
      "[[footnote]]pages note[[/footnote]]",
      "[[/module]]",
      '[[module ListUsers users="."]]',
      "[[html]]users[[/html]]",
      "[[footnote]]users note[[/footnote]]",
      "[[/module]]",
    ].join("\n");

    const document = await processWikitext(source, {
      page: pageContext,
      dataProvider: listPagesProvider({
        fetchListUsers: async () => ({
          user: { number: 1, title: "Alice", name: "alice" },
        }),
      }),
    });

    expect(document.ast["html-blocks"]).toEqual(["top", "pages", "users"]);
    expect(document.ast.footnotes).toHaveLength(3);
    expect(countElements(document.ast.elements, "footnote-block")).toBe(1);
  });

  it("combines initial and module parse diagnostics", async () => {
    const source = [
      '[[module ListPages range="." limit="1"]]',
      "[[code]]module unclosed",
      "[[/module]]",
      "[[div]]",
      "top unclosed",
    ].join("\n");

    const document = await processWikitext(source, {
      page: pageContext,
      dataProvider: listPagesProvider(),
    });

    expect(document.diagnostics.filter((item) => item.code === "unclosed-block")).toHaveLength(2);
  });

  it("keeps only the first explicit footnote block", async () => {
    const source = [
      '[[footnoteblock title="Top"]]',
      '[[module ListPages range="." limit="1"]]',
      '[[footnoteblock title="Generated"]]',
      "[[/module]]",
    ].join("\n");

    const document = await processWikitext(source, {
      page: pageContext,
      dataProvider: listPagesProvider(),
    });

    const blocks = collectElements(document.ast.elements, "footnote-block");
    expect(blocks).toHaveLength(1);
    expect(blocks[0]?.element === "footnote-block" ? blocks[0].data.title : null).toBe("Top");
  });

  it("resolves modules generated through includes across additional passes", async () => {
    const calls: string[] = [];
    const document = await processWikitext(
      ['[[module ListPages range="." limit="1"]]', "%%content%%", "[[/module]]"].join("\n"),
      {
        page: pageContext,
        dataProvider: {
          fetchListPages: async () => {
            calls.push("list-pages");
            return {
              pages: [{ ...pageData(), content: "[[include generated-users]]" }],
              totalCount: 1,
              site: siteContext(),
            };
          },
          fetchInclude: async ({ page }) => {
            calls.push(`include:${page}`);
            if (page === "generated-users") {
              return [
                '[[module ListUsers users="."]]',
                "[[html]]generated user block[[/html]]",
                "[[include generated-tags]]",
                "[[/module]]",
              ].join("\n");
            }
            if (page === "generated-tags") return "[[module TagCloud]]";
            return null;
          },
          fetchListUsers: async () => {
            calls.push("list-users");
            return { user: { number: 1, title: "Alice", name: "alice" } };
          },
          fetchTagCloud: async () => {
            calls.push("tag-cloud");
            return {
              status: "ok",
              tags: [{ tag: "docs", weight: 1 }],
              category: null,
            };
          },
        },
      },
    );

    expect(calls).toEqual([
      "list-pages",
      "include:generated-users",
      "include:generated-tags",
      "list-users",
      "tag-cloud",
    ]);
    expect(document.dependencies.map((item) => item.location.page)).toEqual([
      "generated-users",
      "generated-tags",
    ]);
    expect(document.ast["html-blocks"]).toEqual(["generated user block"]);
    expect(JSON.stringify(document.ast)).not.toContain('"element":"module"');
  });

  it("merges diagnostics emitted while parsing an additional pass", async () => {
    const document = await processWikitext(
      '[[module ListPages range="." limit="1"]]%%content%%[[/module]]',
      {
        page: pageContext,
        dataProvider: {
          fetchListPages: async () => ({
            pages: [{ ...pageData(), content: "[[include generated-users]]" }],
            totalCount: 1,
            site: siteContext(),
          }),
          fetchInclude: async () =>
            '[[module ListUsers users="."]][[code]]generated unclosed[[/module]]',
          fetchListUsers: async () => ({
            user: { number: 1, title: "Alice", name: "alice" },
          }),
        },
      },
    );

    expect(document.diagnostics.some((item) => item.code === "unclosed-block")).toBe(true);
  });

  it("stops without a limit diagnostic when a generated module has no provider", async () => {
    const document = await processWikitext('[[module ListUsers users="."]]x[[/module]]', {
      page: pageContext,
    });

    expect(JSON.stringify(document.ast)).toContain('"module":"list-users"');
    expect(document.diagnostics.some((item) => item.code === "module-resolution-limit")).toBe(
      false,
    );
  });

  it("keeps the initial IfTags resolution without data providers", async () => {
    const document = await processWikitext(
      "[[iftags +component]]visible[[else]]hidden[[/iftags]]",
      { page: pageContext },
    );

    expect(JSON.stringify(document.ast)).toContain("visible");
    expect(JSON.stringify(document.ast)).not.toContain('"element":"if-tags"');
  });

  it("stops self-generating modules after five passes with a diagnostic", async () => {
    let calls = 0;
    const generated = '[[module ListPages range="." limit="1"]]%%content%%[[/module]]';
    const document = await processWikitext(generated, {
      page: pageContext,
      dataProvider: {
        fetchListPages: async () => {
          calls++;
          return {
            pages: [{ ...pageData(), content: "[[include generated-loop]]" }],
            totalCount: 1,
            site: siteContext(),
          };
        },
        fetchInclude: async () => generated,
      },
    });

    expect(calls).toBe(5);
    expect(JSON.stringify(document.ast)).toContain('"module":"list-pages"');
    expect(document.diagnostics.some((item) => item.code === "module-resolution-limit")).toBe(true);
  });

  it("reports an include expansion limit", async () => {
    const document = await processWikitext("[[include a]]", {
      page: pageContext,
      includeMaxIterations: 1,
      dataProvider: {
        fetchInclude: async ({ page }) => `[[include ${page === "a" ? "b" : "a"}]]`,
      },
    });

    expect(document.diagnostics.some((item) => item.code === "include-resolution-limit")).toBe(
      true,
    );
  });
});

function countElements(elements: Element[], name: Element["element"]): number {
  return collectElements(elements, name).length;
}

function collectElements(elements: Element[], name: Element["element"]): Element[] {
  const found: Element[] = [];
  for (const element of elements) {
    if (element.element === name) found.push(element);
    if (element.element === "container")
      found.push(...collectElements(element.data.elements, name));
  }
  return found;
}
