import { realpathSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);

function git(...args: string[]): string | null {
  if (Bun.which("git") === null) return null;
  const result = Bun.spawnSync(["git", ...args], { cwd: fileURLToPath(root) });
  return result.exitCode === 0 ? result.stdout.toString().trim() : null;
}

export async function generateBuildInfo(): Promise<void> {
  const topLevel = git("rev-parse", "--show-toplevel");
  const ownRepository = topLevel !== null && realpathSync(topLevel) === realpathSync(root);
  const sha = ownRepository ? git("rev-parse", "HEAD") : null;
  const status = sha !== null ? git("status", "--porcelain", "--untracked-files=normal") : null;
  const dirty = status === null ? null : status.length > 0;

  for (const name of ["ast", "parser", "render", "decompiler", "runtime"]) {
    const { version } = await Bun.file(new URL(`packages/${name}/package.json`, root)).json();
    const output = Bun.file(new URL(`packages/${name}/src/build-info.generated.ts`, root));
    const source = `// Generated by bun run build:info. Do not edit.
/** Build-time package metadata; unavailable Git information is null. */
export const buildInfo: Readonly<{
  version: string;
  sha: string | null;
  dirty: boolean | null;
}> = Object.freeze({
  version: ${JSON.stringify(version)},
  sha: ${JSON.stringify(sha)},
  dirty: ${JSON.stringify(dirty)},
});
`;
    if (!(await output.exists()) || (await output.text()) !== source) {
      await Bun.write(output, source);
    }
  }
}

if (import.meta.main) await generateBuildInfo();
