import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const target = "packages/render/src/messages.generated.ts";
const extracted = Bun.spawnSync(
  [
    process.execPath,
    "x",
    "--bun",
    "--no-install",
    "formatjs",
    "extract",
    "packages/render/src/elements/**/*.ts",
    "--additional-function-names",
    "text,html",
    "--format",
    "simple",
    "--throws",
    "--preserve-whitespace",
  ],
  { cwd: root, stdout: "pipe", stderr: "inherit" },
);
if (extracted.exitCode !== 0) process.exit(extracted.exitCode);

const messages = JSON.parse(extracted.stdout.toString());
const source = `// Generated by bun run messages:extract. Do not edit.\nexport const renderMessages = ${JSON.stringify(messages, null, 2)} as const;\n`;
const formatted = Bun.spawnSync(
  [process.execPath, "x", "--no-install", "oxfmt", "--stdin-filepath", target],
  { cwd: root, stdin: Buffer.from(source), stdout: "pipe", stderr: "inherit" },
);
if (formatted.exitCode !== 0) process.exit(formatted.exitCode);

const output = formatted.stdout.toString();
if (process.argv.includes("--check")) {
  if ((await Bun.file(resolve(root, target)).text()) !== output) {
    console.error("Renderer messages are out of date. Run bun run messages:extract.");
    process.exit(1);
  }
} else {
  await Bun.write(resolve(root, target), output);
}
