// Generated by bun run messages:extract. Do not edit.
export const renderMessages = {
  "bibliography.title": "Bibliography",
  "collapsible.hide": "– hide block",
  "collapsible.show": "+ show block",
  "embed.invalid": "Sorry, no match for the embedded content.",
  "footnote.title": "Footnotes",
  "gallery.empty": "Sorry, we couldn't find any images attached to this page.",
  "include.missing":
    'Included page "{page}" does not exist (<createLink>create it now</createLink>)',
  "module.join": "Join",
  "module.unknown":
    "[[module <emphasis>{name}</emphasis>]] No such module, please <documentationLink>check available modules</documentationLink> and fix this page.",
  "rate.cancel": "Cancel my vote",
  "rate.down": "I don't like it",
  "rate.label": "rating",
  "rate.up": "I like it",
  "toc.fold": "Fold",
  "toc.title": "Table of Contents",
  "toc.unfold": "Unfold",
  "user.anonymous": "Anonymous",
} as const;
